### ISSUE TITLE
Can the watermark be changed?

### ISSUE THREAD

**Issue by ProjectDent** [kaltura/player-sdk-native-ios#107]
I'd like to be able to change the watermark over the video without needing access to the admin console. I can't see any mention of it here:
http://player.kaltura.com/docs/api

Is this possible?

**Comment by kaltura-hooks** [comment]
Hi @ProjectDent,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue and post at:
https://forum.kaltura.org/c/community-forums/player-sdk

Thank you in advance!

**Comment by jessp01** [comment]
Hello,
Kaltura supports two ways of embedding watermarks:
 
- on the player
- on the video itself during transcoding

Neither of these require access to the Admin Console but to access Studio you need KMC access and to use the API, you need the partner's admin secret.

To do so at the player level, you can either go into KMC->Studio, select your player and type "watermark" in the searchbox or you can use the API with uiconf.update()
adding something like:
		"logo": {
			"href": "http://somedomain",
			"title": "XXXX",
			"plugin": true,
			"img": "http://somedomain/images/xxxx-Watermark.png"
		},

to the player's existing JSON under:
"plugins": {

You can get the existing config by calling:
```
uiconf.get(player_uiconf_id)
```

For watermarking during transcoding, look at: 
https://forum.kaltura.org/t/watermark-upon-transcoding/3195

**Comment by kaltura-hooks** [comment]
Hi @ProjectDent,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue and post at:
https://forum.kaltura.org/c/community-forums/player-sdk

Thank you in advance!

**Comment by kaltura-hooks** [comment]
Hi @ProjectDent,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue and post at:
https://forum.kaltura.org/c/community-forums/player-sdk

Thank you in advance!
