### ISSUE TITLE
changeMedia throws exception

### ISSUE THREAD

**Issue by jabberdabber** [kaltura/player-sdk-native-ios#123]
Hi,

We're using v2.2.0 of the SDK.

We’re attempting to use the ‘changeMedia’ method in the KPViewController class to change videos. We have a test app in which the KPViewController object is configured to play a video in the parent controller's viewDidAppear method. We also have a button that when tapped its action method calls ‘changeMedia’ to change the video that is being played by the KPViewController object.

We’ve run into a problem in which an exception is thrown when we call ‘changeMedia’:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7f8101e51ae0 of class AVPlayerItem was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7f8101f794f0> (
<NSKeyValueObservance 0x7f8101e670d0: Observer: 0x7f8101c151d0, Key path: playbackBufferEmpty, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x7f8101e54600>
<NSKeyValueObservance 0x7f8101e74ec0: Observer: 0x7f8101c151d0, Key path: playbackLikelyToKeepUp, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x7f8101e54790>
<NSKeyValueObservance 0x7f8101def900: Observer: 0x7f8101c151d0, Key path: playbackBufferFull, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x7f8101e72a30>
)'

In looking through the SDK, we think the source of this error may be a failure call 'unregisterForPlaybackNotification' in the 'prepareToPlayAsset' method inside of the KPlayer class, but we're not sure. 

Any help is appreciated, thank you.

**Comment by kaltura-hooks** [comment]
Hi @jabberdabber,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @jabberdabber,

This issue is already fixed and will be released on our next version this weak.
For now You can use the "development" branch and see that it works for you.

If you are using cocoapods, you can point our "development" branch in the following way:
             
    pod 'KalturaPlayerSDK', :git => 'https://github.com/kaltura/player-sdk-native-ios.git', :branch => 'develop'

Thanks!
