### ISSUE TITLE
addConfigKey not working

### ISSUE THREAD

**Issue by jonigl** [kaltura/player-sdk-native-ios#158]
Hi,

I've just updated my player to kWidget 2.42 but since thet I can't get `addConfigKey` to work. (KalturaPlayerSDK (2.3.2) by Pods).

I'm using addConfigKey to hide some elements of the player to archive a chromeless version:

```
        [config addConfigKey:@"controlBarContainer.plugin" withValue:@"false"];
        [config addConfigKey:@"EmbedPlayer.HidePosterOnStart" withValue:@"true"];
        [config addConfigKey:@"topBarContainer.plugin" withValue:@"false"];
        [config addConfigKey:@"largePlayBtn.plugin" withValue:@"false"];
        [config addConfigKey:@"loadingSpinner.plugin" withValue:@"flase"];
```

also `[config addConfigKey:@"autoPlay" withValue:@"true"];` for autoplay.

This config worked but since the update it doesn't.

Any ideas?

Thanks!
Jonathan

**Comment by kaltura-hooks** [comment]
Hi @jonigl,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @jonigl ,

Can you send me the domain you are using? and all your config init params?

Thanks!

**Comment by jonigl** [comment]
Hi @ElizaSapir,

This is my configuration:

````
- (KPViewController *)player {
    if (!_player) {
        // Account Params
        KPPlayerConfig *config = [[KPPlayerConfig alloc] initWithServer:@"http://kaltura.com"
                                                               uiConfID:@"34494681"
                                                              partnerId:@"2113721"];
        playlistIndex = 0;
        playlist = [NSArray arrayWithObjects: @"1_07xj69s6",@"1_t7ftad3f",@"1_ca5xzw36",@"1_xo9lr5dz",@"1_y1or1817",@"1_49aai1r2",@"1_6o67ru53",@"1_m22igpgy", nil];
        [config setEntryId: playlist[playlistIndex]];
        [config addConfigKey:@"autoPlay" withValue:@"true"];
        [config addConfigKey:@"controlBarContainer.plugin" withValue:@"false"];
        [config addConfigKey:@"EmbedPlayer.HidePosterOnStart" withValue:@"true"];
        [config addConfigKey:@"topBarContainer.plugin" withValue:@"false"];
        [config addConfigKey:@"largePlayBtn.plugin" withValue:@"false"];
        [config addConfigKey:@"loadingSpinner.plugin" withValue:@"false"];
        _player = [[KPViewController alloc] initWithConfiguration:config];
        NSLog(@"PLAYER CONFIGURED");
    }
    return _player;
}
```

Thanks!

**Comment by noamtamim** [comment]
@jonigl can we close this issue?

**Comment by jonigl** [comment]
@noamtamim yes because I'm current using kWidget 2.40

Thanks!
