### ISSUE TITLE
Minimum iOS for KalturaPlayerSDK (2.3.2)?

### ISSUE THREAD

**Issue by jonigl** [kaltura/player-sdk-native-ios#162]
Hi,

I would like to know wich is the minimum iOS versión for KalturaPlayerSDK (2.3.2). 

Thanks!

Regards,

Jonathan

**Comment by kaltura-hooks** [comment]
Hi @jonigl,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @jonigl ,

It's iOS 8.

Best,
Eliza

**Comment by jonigl** [comment]
Hi @ElizaSapir!

How strange, I thought it was iOS 9.0 because when I tried to build an app using KalturaPlayerSDK (2.3.2) and run it in an iPhone using iOS 8.4 it didn't work. I saw at the console this output: `dyld: Symbol not found: _OBJC_CLASS_$_AVPictureInPictureController`. So I searched on the internet this class and I could found that is available in iOS 9.0 and later (check this [link](https://developer.apple.com/library/ios/documentation/AVKit/Reference/AVPictureInPictureController_Class/)). Also I found that this class (AVPictureInPictureController) is present in the kPlayer Class.

How I can skip this problem? Thanks in advance!

Regards,
Jonathan
