### ISSUE TITLE
libWViPhoneAPI.a missing required architecture x86_64

### ISSUE THREAD

**Issue by jonigl** [kaltura/player-sdk-native-ios#163]
Hi! 

I have this warning in my project:

`ld: warning: ignoring file xxx/xxx/Pods/KalturaPlayerSDK/libWViPhoneAPI.a, missing required architecture x86_64 in file xxx/xxx/Pods/KalturaPlayerSDK/libWViPhoneAPI.a (3 slices)`

How can I resolve this?

**Comment by kaltura-hooks** [comment]
Hi @jonigl,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @jonigl,

Can you mention the version you are using?

Thanks!

**Comment by jonigl** [comment]
Hi @ElizaSapir!

Yes, I'm using KalturaPlayerSDK (2.3.2) installed by Pods.

Thanks!

Best!
Jonathan

**Comment by ElizaSapir** [comment]
@jonigl ,

your content is drm protected?

**Comment by jonigl** [comment]
@ElizaSapir 
No, my content is not drm protected. 
This is my warning: 
<img width="1174" alt="warning" src="https://cloud.githubusercontent.com/assets/4612832/15218883/27ba8b32-1838-11e6-95d8-ec6e219f073a.png">

Best!
Jonathan

**Comment by ElizaSapir** [comment]
@jonigl ,

Are you working with cocoapods or you imported our sdk statically?
If statically can you please try and compile kaltura player sdk and then your project?

Thanks!

**Comment by jonigl** [comment]
@ElizaSapir,

i'm working wit cocoapods. Is there anything I can do to resolve this?

Thanks! :)
Jonathan

**Comment by ElizaSapir** [comment]
@jonigl 

Try  pod update, it now supposed to be an issue.

**Comment by jonigl** [comment]
Hey @ElizaSapir I tried pod update and works :)

Tomorrow I will be doing more testing and if It works I will close this issue.

Best!
Jonathan

**Comment by jonigl** [comment]
Hi @ElizaSapir 

I was testing the app and I found that the warning message is only appears when I build and then run an iOS Simulator and it doesn't appears in a real device. If you consider this warning normal feel free to close this issue :)

Thanks!
Jonathan
