### ISSUE TITLE
Error: The request timed out.

### ISSUE THREAD

**Issue by jonigl** [kaltura/player-sdk-native-ios#169]
Hi!

Sometimes my app is getting this output error:

```
::Error:: -[KPControlsUIWebview webView:didFailLoadWithError:] (line:155)
Error: The request timed out.
```

Is there any way to solve this, perhaps restarting the request, because probably is an internet connections issue but restart the request would help.

Thanks!
Jonathan

**Comment by kaltura-hooks** [comment]
Hi @jonigl,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @jonigl,

Do you have steps to reproduce?

Thanks!

**Comment by jonigl** [comment]
@ElizaSapir 

I don't have steps to reproduce it at the moment because it is very unpredictable, but usually it happens when I have problems with my internet connection.

Best
Jonathan

**Comment by earthcore** [comment]
Hi,

I encountered a similar error when I load the SDK player in iOS 8.1 and 8.4, but it is ok in iOS 9.3.  Will like to check if the Kaltura SDK support iOS 8?
 
[KPControlsUIWebview webView:didFailLoadWithError:] (line:160)
Error: The network connection was lost.

Thanks and regards,

LW

**Comment by ElizaSapir** [comment]
Hey @jonigl ,

You can use "changeConfiguration" method under KPViewController with the same config and this will reload the webview layer (restart the request).

Best,
Eliza

cc @OrenMe , @itaykinnrot
