### ISSUE TITLE
"The access to this service is forbidden" when attempting to register an asset

### ISSUE THREAD

**Issue by ProjectDent** [kaltura/player-sdk-native-ios#171]
Following on from [this issue](https://github.com/kaltura/player-sdk-native-ios/issues/168), and using the pull request I submitted, as it's the only way to register an asset without it crashing...

The request made to Kaltura API gives an error response:

```
{
  "code": "SERVICE_FORBIDDEN_CONTENT_BLOCKED",
  "message": "The access to this service is forbidden since the specified partner is blocked",
  "objectType": "KalturaAPIException",
  "args": []
}
```
Using the API for other requests, such as streaming video, or indeed downloading that same video, does work. I've attached a screenshot of the request from inside of Postman, so you can ensure I'm using the correct parameters. Without most of them it would give an error pointing to them as being missing, so I do believe them all to be correct.

![screen shot 2016-05-13 at 19 32 57](https://cloud.githubusercontent.com/assets/1865635/15258098/84e4d8b2-1941-11e6-85a9-0e14cbb1f96c.png)

**Comment by kaltura-hooks** [comment]
Hi @ProjectDent,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ProjectDent** [comment]
We were using an incorrect partner ID.
