### ISSUE TITLE
removePlayer not working

### ISSUE THREAD

**Issue by jonigl** [kaltura/player-sdk-native-ios#180]
Hi,
Could it be that this #30 problem keeps happening?
Because I use [self.player removePlayer]; but when I instantiate KPViewController again I can hear the old video playing in the background (no present at the scene) with the new player (currently playing at the scene).

How can I remove the player between viewcontrollers?

Thanks,
Jonathan

**Comment by kaltura-hooks** [comment]
Hi @jonigl,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @jonigl ,

Did you remove it and set it to nil?

Thanks,

Eliza

**Comment by jonigl** [comment]
@ElizaSapir yes I did it :) thanks!
