### ISSUE TITLE
Unable to view VAST ad

### ISSUE THREAD

**Issue by earthcore** [kaltura/player-sdk-native-ios#184]
Hi, 

When the server sent my iOS app a video with VAST ad, the pre-roll ad is not shown and the spinner keeps spinning as if it is loading.  However, when we click on play, the video plays as per normal.  Our android counterpart says they also encountered this issue previously, but after updating the sdk from the trunk code, it works fine now.   However, using the master branch for iOS sdk still does not resolve the issue.  Will you be able to advise if we set anything wrongly?

            let config = KPPlayerConfig(server: params[1], uiConfID: params[2], partnerId: params[3])
            config.entryId = params[4]
            config.ks = params[7]
            config.cacheSize = 100
            config.addConfigKey("autoPlay", withValue: "true")
            config.addConfigKey("watermark", withDictionary: ["plugin":false])
            config.addConfigKey("doubleClick.plugin", withValue: "true")
            config.addConfigKey("doubleClick.adTagUrl", withValue: "https://pubads.g.doubleclick.net/gampad/ads?sz=400x300&iu=/35380761/KMC-video&ciu_szs=300x250,728x90&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]")
            
            KalturaPlayer = KPViewController(configuration: config)
            
            videoWidth = CGFloat(NSNumberFormatter().numberFromString(params[5])!)
            videoHeight = CGFloat(NSNumberFormatter().numberFromString(params[6])!)
            
            KalturaPlayer!.loadPlayerIntoViewController(self)

**Comment by ElizaSapir** [comment]
Hey @earthcore ,

Your code looks ok.
Please send me your config params including ks and entry id and i will try to test on my side now.
Then will let you know if there is an issue on our side or something wrong on your side.

Thanks!

**Comment by kaltura-hooks** [comment]
Hi @earthcore,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by earthcore** [comment]
Hi,

Thanks for the prompt reply, my parameters are as follow:

server: https://cdnapisec.kaltura.com
uiConfID: 34434332
partnerId: 1992341
entryId: 0_irf7azp5
width: 328
height: 185
ks: djJ8MTk5MjM0MXxAP9ZNbR_RUBbeuVvTDy00p-DKHuZhs50r_EJ9Ck9XTx-rOvGZ2pBEUiSQLcBKth4CQ7oNkzXkgt1TmFMZl9p7y7zfv0ICcQ93fZQ2OSVexCOA7RB4NFFosJo4csjQGqvmOrUwFEKCVvd4EI6wcTS6

**Comment by earthcore** [comment]
Sorry I just realised I need to include this library too:

pod 'GoogleAds-IMA-iOS-SDK’ , '~> 3.1.0’

Problem solved :)

**Comment by ElizaSapir** [comment]
great thanks!
