### ISSUE TITLE
Playback Rate Selector Not Working

### ISSUE THREAD

**Issue by dcdspace** [kaltura/player-sdk-native-ios#207]
I am trying to add the playback rate selector to my video player, and it is not working in iOS. My configuration code is this: 

```
      [config addConfigKey:@"sourceSelector.plugin" withValue:@"true"];
        [config addConfigKey:@"sourceSelector.displayMode" withValue:@"size"];
       [config addConfigKey:@"playbackRateSelector.plugin" withValue:@"true"];
       [config addConfigKey:@"playbackRateSelector.position" withValue:@"after"];
      [config addConfigKey:@"playbackRateSelector.loadingPolicy" withValue:@"onDemand"];
        [config addConfigKey:@"playbackRateSelector.defaultSpeed" withValue:@"2"];
        [config addConfigKey:@"playbackRateSelector.speeds" withValue:@".5,.75,.1,.15,2"];
        [config addConfigKey:@"playbackRateSelector.relativeTo" withValue:@"PlayerHolder"];
```

**Comment by kaltura-hooks** [comment]
Hi @dcdspace,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @dcdspace,

Playback Rate is not supported on our player SDK.
Please look on the below doc to see what is supported on iOS SDK,
https://vpaas.kaltura.com/documentation/Mobile-Video-Player-SDKs/Player-Plugins-in-the-SDK-Supported-plugins.html

Best,
Eliza

cc @itaykinnrot , @OrenMe
