### ISSUE TITLE
Missing KPCacheConfig.h

### ISSUE THREAD

**Issue by jabberdabber** [kaltura/player-sdk-native-ios#209]
Hi, when we install the SDK by downloading it, we get this error when compiling our project:

/Users/Les/GitHub/video-ios/player-sdk-native-ios-master/KALTURAPlayerSDK/KPPlayerConfig.h:11:9: 'KPCacheConfig.h' file not found

We found the solution was to add KPCacheConfig.h to the list of files to copy in the SDK's Build Phases config.

**Comment by kaltura-hooks** [comment]
Hi @jabberdabber,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @jabberdabber,

Our recommandation is to use cocoapods.

Best,
Eliza
