### ISSUE TITLE
How to track video bitrate ?

### ISSUE THREAD

**Issue by WillsAtIOS** [kaltura/player-sdk-native-ios#220]
Hi I'm using IOS SDK in our application, We want to enable to Video bitrate options. So we did it in Android using the fallowing method. 
But didn't find any way to implement in IOS, could anyone please help me out in this ?

mPlayer.getTrackManager().switchTrack(TrackType.VIDEO, 3); This method we used in android

**Comment by kaltura-hooks** [comment]
Hi @WillsAtIOS,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @WillsAtIOS ,

Please read the answer on our Forum:
https://forum.kaltura.org/t/how-to-track-video-bitrate/5607

Thanks!

cc @OrenMe
