### ISSUE TITLE
sending hideClosedCaptions event won't make cc disappear

### ISSUE THREAD

**Issue by mikishab** [kaltura/player-sdk-native-ios#228]
We want to disable closed captions by default for all videos.

In order to do so we tried sending hideClosedCaptions notification on several places:
- ccDataLoaded event fired
- firstPlay event fired
- playerPlaybackStateDidChange to KPMediaPlaybackStateLoaded

none of those worked 100% of time

A sample project where you can see the problem:
https://github.com/mikishab/KalturaDemoApp

**Comment by kaltura-hooks** [comment]
Hi @mikishab,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by imrimarmor** [comment]
28 days since the original issue was posted. Any thoughts?

**Comment by ElizaSapir** [comment]
v2.49 will be released in a week and a half, this version contains a fix for this issue.

cc @OrenMe
