### ISSUE TITLE
Play/Pause – if you send pause event and then play in quick succession - player wont play

### ISSUE THREAD

**Issue by mikishab** [kaltura/player-sdk-native-ios#230]
We have native buttons for play and pause,
We call the corresponding KPController's methods to do so.

When sending a pause event and then a play event quickly, the player won't play, even after waiting a long time.

A sample project where you can see the problem:
https://github.com/mikishab/KalturaDemoApp

**Comment by kaltura-hooks** [comment]
Hi @mikishab,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by piterwilson** [comment]
@kaltura-hooks I have the same problem in a swift project. I have checked the "how to" report and issue and there it says:

> "Check to see if your issue is a known issue."
 It is not a known issue.

> "Isolate the issue."

 I believe @mikishab  has done that. I have the same issue and i also have sample code i have shared with your staff privately as it contains some sensitive commercial information.

I will now address the following points:

**Provide case specific information:**

When using the native player controls (not the html layer controls) succesive calls to player.playerController.play() and player.playerController.pause() seems to fail at random moments.

**Include additional helpful information:**

I have already been in touch with one of the developers @ElizaSapir who told me that the communication with the html layer can be slow and that to avoid the problem i should wait for the player to actually change state to `.Playing` / `.Pause` before calling `player.playerController.play()` and `player.playerController.pause()` again. 

I have done this and even though it helps, the player will eventually gets stuck given enough play/pause attempts. Not an implementation issue as far as i can tell. 

Another useful information is that it's important that you set 

`config.addConfigKey("doubleClick.plugin", withValue: "false")`

If you are not using an ad exactly at that moment.

Other than that, i don't know what else can be done for this issue to be seriously addressed and not just ignored and given standard non-answer.

If there is more that can be done to help you track this issue please let me know ill gladly provide more info, im sure @mikishab will too. 

I know you work hard but please don't ignore the issues people bring up with standard non-answer. I have seen other tickets where people get angry because things are not addressed directly.

Thanks

**Comment by imrimarmor** [comment]
28 days since the original issue was posted. Any thoughts?

**Comment by ElizaSapir** [comment]
Hey @mikishab,

We made some optimizations that are related to this issue.
These optimizations will be included on v2.49 html5 version, since it's not published yet as production release, and just to make sure it resolves the issues on your side you can test it with:
http://kgit.html5video.org/tags/v2.49.rc12/mwEmbedFrame.php

please put the above url as server url (when creating KPPlayerConfig object).
The moment v2.49 will be released you can use it as production release.

Best,
Eliza

cc @itaykinnrot , @OrenMe
