### ISSUE TITLE
embedLoaderUrl test failing

### ISSUE THREAD

**Issue by jabberdabber** [kaltura/player-sdk-native-ios#243]
Hi, we're using v2.4.9 of the SDK.

We're seeing an if statement fail in KPPlayerConfig.m:

if (![embedLoaderUrl hasSuffix:@"/mwEmbedLoader.php"]) {

This test fails because while the embedLoaderUrl has a string that contains "mwEmbedLoader.php", it's not at then end, so the suffix test fails, e.g.:

http://kgit.html5video.org/tags/v2.48.7/mwEmbedLoader.php/uiconf_id/xxxxxxxx/wid/xxxxxxxxx

(obfuscated to remove player and partner ID)

This prevents the video from playing.

**Comment by kaltura-hooks** [comment]
Hi @jabberdabber,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by itaykinnrot** [comment]
@jabberdabber  - we're checking it and get back soon - Thanks!
@noamtamim

**Comment by itaykinnrot** [comment]
@jabberdabber i'm not sure i understand where you are getting this request - this is what you use as server url?

**Comment by jabberdabber** [comment]
@itaykinnrot Hi, we're using this as our server URL: http://cdnapi.kaltura.com

Example usage:

KPPlayerConfig *config = [[KPPlayerConfig alloc] initWithServer:@"http://cdnapi.kaltura.com"

The Kaltura Player SDK code creates the request that gets the URL quoted in my original post. See KPPlayerConfig.m, line: 283

/ Load uiConf from Kaltrua API, get the path from there.
    [self loadUIConfWithCompletionHandler:^(NSDictionary * _Nullable uiConf, NSError * _Nullable error) {
        if (!uiConf) {
            if (!cachedServerUrl) {
                KPLogError(@"Failed loading uiConf: %@", error);
                _errorResolvingPlayerURL = YES;
                handler(NO);
            }
            return; // handler was already called, based on cache
        }
        
        NSString *embedLoaderUrl = uiConf[@"html5Url"];

The value for the embedLoaderUrl variable at this point for us is:

http://kgit.html5video.org/tags/v2.48.7/mwEmbedLoader.php/uiconf_id/xxxxxxxx/wid/xxxxxxxxx

(obfuscated to remove player and partner ID)

Following this is the suffix test that fails.

**Comment by ElizaSapir** [comment]
Hey @jabberdabber,

Can you please use the following rc tag:
https://github.com/kaltura/player-sdk-native-ios/releases/tag/v2.6.0.rc3

And let us know if it resolves the issue you described?
And please make sure you follow our document that explains how to create an instance of our player and set it up.
https://vpaas.kaltura.com/documentation/Mobile-Video-Player-SDKs/iOS-Getting-Started.html

Production release of v2.6.0 will be released tomorrow.

Thanks,
Eliza

cc @OrenMe , @itaykinnrot

**Comment by ElizaSapir** [comment]
Supposed to be fixed on our latest version.
