### ISSUE TITLE
Full Screen Videos are getting stuck in a Bad network connection

### ISSUE THREAD

**Issue by amol-c** [kaltura/player-sdk-native-ios#252]
Problem Defintion:
The below happens in a FullScreen mode and when you are scrubbing.

1. When we are in a bad network area, the player starts acting weird and freezes indefinitely.

2. The `func kPlayer(player: KPViewController!, playerPlaybackStateDidChange state: KPMediaPlaybackState)` keeps getting called with `pause` and `Playing` stating back to back.

3. The `KPlayer play` keeps getting called indefinitely and freezes the UI.

Please refer the screenshot for callstack.

![screen shot 2016-11-21 at 10 19 25 am](https://cloud.githubusercontent.com/assets/2050256/20488057/aa079fb6-afd3-11e6-8cb1-e6a664146c4a.png)

The screenshot below shows the call `pause` and `play` sending back to back to the `KPlayer`, which seems to be causing the continuous play - pause issue.

![screen shot 2016-11-21 at 10 30 50 am](https://cloud.githubusercontent.com/assets/2050256/20488495/3a576654-afd5-11e6-95a5-ba8774be73ea.png)

**Comment by kaltura-hooks** [comment]
Hi @amol-c,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by amol-c** [comment]
Looks like the issue is the additional call to 
![screen shot 2016-11-21 at 11 10 34 am](https://cloud.githubusercontent.com/assets/2050256/20490055/a6039f44-afda-11e6-96e6-e059eac10e56.png)

**Comment by ElizaSapir** [comment]
Hey @amol-c ,

Since we found many issues on WKWebView we moved back to UIWebView.
Please switch to our latest version and the issues won't happen any more.

Thanks!

**Comment by amol-c** [comment]
Thanks. We will update it in our next release.
