### ISSUE TITLE
Disable Captions

### ISSUE THREAD

**Issue by joaofranca** [kaltura/player-sdk-native-ios#260]
Hi,

Is it possible to disable all captions? How?

**Comment by kaltura-hooks** [comment]
Hi @joaofranca,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey @joaofranca ,

You can do it via KMC by desabling "closedCaptions" plugin or by code:

```objc
[config addConfigKey:@"closedCaptions.plugin" withValue: @"false"];
```

Thanks!
