### ISSUE TITLE
How to play manifest.mpd file through kaltura

### ISSUE THREAD

**Issue by suresh777** [kaltura/player-sdk-native-ios#261]
Actually our backend side we configured widevine drm,we tested in android it's working,similarly if we test in ios,how to pass manifest.mpd kaltura player

**Comment by kaltura-hooks** [comment]
Hi @suresh777,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment]
Hey,

@suresh777  .mpd doesn't supported on iOS, so the answer is -> it's not possible.
you can use our SDK that support Widevine Classic or FairPlay

Thanks!

cc @noamtamim
