### ISSUE TITLE
The access to this service is forbidden since the specified partner is blocked

### ISSUE THREAD

**Issue by JustinGuo7** [kaltura/player-sdk-native-ios#268]
Hi,

We met the error message "The access to this service is forbidden since the specified partner is blocked” when play a video from Kaltura, also can't log into Kaltura through our account, even after reset password. Please kindly help to investigate and let us know the cause.

Account ID: zzhcch211@126.com
Partner ID: 2276421

Thanks.

**Comment by kaltura-hooks** [comment]
Hi @JustinGuo7,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by JustinGuo7** [comment]
Already got feedback from Kaltura, thanks for the email notification.
