### ISSUE TITLE
Double Click plugin causes player to hang

### ISSUE THREAD

**Issue by jabberdabber** [kaltura/player-sdk-native-ios#272]
Hi,

The double click plugin causes the player to hang. It just endlessly spins after you click the play button.

I've created a simple single view app to demonstrate the problem. Here is the player property implementation. It's taken from Kaltura's example with the double click plugin added. The ad tag is from Kaltura's demo example located here:

[Kaltura DoubleClick Example](http://player.kaltura.com/docs/DoubleClick)

```
- (KPViewController *)player {
    if (!_player) {
        // Account Params
        KPPlayerConfig *config = [[KPPlayerConfig alloc] initWithServer:@"http://cdnapi.kaltura.com"
                                                               uiConfID:@"26698911"
                                                              partnerId:@"1831271"];
        
        // Video Entry
        config.entryId = @"1_o426d3i4";
        
        [config addConfigKey:@"doubleClick.adTagUrl" withValue:@"http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=%2F3510761%2FadRulesSampleTags&ciu_szs=160x600%2C300x250%2C728x90&cust_params=adrule%3Dpremidpostwithpod&impl=s&gdfp_req=1&env=vp&ad_rule=1&vid=12345&cmsid=3601&output=xml_vast2&unviewed_position_start=1&url=[referrer_url]&correlator=[timestamp]"];
        [config addConfigKey:@"doubleClick.plugin" withValue:@"true"];
        
        // Setting this property will cache the html pages in the limit size
        config.cacheSize = 0.8;
        _player = [[KPViewController alloc] initWithConfiguration:config];
    }
    return _player;
}
```

**Comment by kaltura-hooks** [comment]
Hi @jabberdabber,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by OrenMe** [comment]
Thank you for reporting the issue.
Issue is fixed in https://github.com/kaltura/mwEmbed/releases/tag/v2.69.3
