### ISSUE TITLE
Player should deallocate when KPViewController is deallocated

### ISSUE THREAD

**Issue by tbrannam** [kaltura/player-sdk-native-ios#30]
there are some circular memory dependencies that keep the KPlayer active after the KPViewController has been removed.

If a KPViewController is popped from the application stack - the KPViewController is not getting deallocated - and since it wasn't getting deallocated the video would continue to execute.

**Comment by jonigl** [comment]
Hi,
Could it be that this problem keeps happening?
because I use `[self.player removePlayer];` but when I instantiate KPViewController again I can hear the old video playing in the background (no present at the scene) with the new player (currently playing at the scene).

How can I remove the player between viewcontrollers?

Thanks,
Jonathan
