### ISSUE TITLE
iOS 9 : WebKit discarded an uncaught exception 

### ISSUE THREAD

**Issue by palaniraja** [kaltura/player-sdk-native-ios#51]
I followed the steps and I don't see a video. All i see is the following error. Is it something with iOS9? (I am running xcode 7.1)

```

HTTP:: http://cdnapi.kaltura.com/p/1831271/sp/183127100/embedIframeJs/uiconf_id/26698911/entry_id/1_o426d3i4?wid=_1831271&entry_id=1_o426d3i4&iframeembed=true

*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> *** -[NSBundle initWithURL:]: nil URL argument

```
Just created a simple master detail project for iphone and viewdidappear on detailviewcontroller. (branch 2.0.1) as the master throw build error.(issue 48)

**Comment by kaltura-hooks** [comment]
Hi @palaniraja,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by itaykinnrot** [comment]
Make sure you are using https on iOS 9 - https://cdnapisec.kaltura.com/

**Comment by palaniraja** [comment]
Same even after https:

```

2015-10-23 16:15:41.773 testkaltura[83722:795494] HTTP:: https://cdnapi.kaltura.com/p/1831271/sp/183127100/embedIframeJs/uiconf_id/26698911/entry_id/1_o426d3i4?wid=_1831271&entry_id=1_o426d3i4&iframeembed=true
2015-10-23 16:15:41.787 testkaltura[83722:795494] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> *** -[NSBundle initWithURL:]: nil URL argument

```

**Comment by palaniraja** [comment]
Hi 
Any update on this? or 
Someone point me to a latest sample code which I can test with my kaltura player config?

**Comment by kaltura-hooks** [comment]
Hi @palaniraja,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by ElizaSapir** [comment]
Hi @palaniraja,

I can't reproduce this issue, please try our new version v2.0.6 and let us know if it works for you:
https://github.com/kaltura/player-sdk-native-ios/releases

* If it does not work for you please share your test app if  it's possible

* Now we support cocoapods if you prefer you can use https://cocoapods.org/pods/KalturaPlayerSDK

**Comment by palaniraja** [comment]
SDK v2.0.8 seems to play the content without any issue. But requires the base sdk to be 8.0 or higher.

I think due to my deployment target set to 7.0 it download older version via cocoa pods. 

Closing the issue.

**Comment by jonigl** [comment]
I'm using SDK v2.3.3 and i have the same issue. My project has iOS Deployment Target 9.2 and KALTURAPlayerSDK iOS Deployment Target 8.2.

This is my current output: 

> 2016-03-14 17:10:47.855 kalturaPlayer[12927:1633694] NSRect: {{0, 0}, {375, 667}}
> 2016-03-14 17:10:47.870 kalturaPlayer[12927:1633694] HTTP:: http://vodgc.com/p/109/sp/10900/embedIframeJs/uiconf_id/23448994/entry_id/0_nex4tg0d?wid=_109&uiconf_id=23448994&entry_id=0_nex4tg0d&iframeembed=true#localContentId=
> 2016-03-14 17:10:47.871 kalturaPlayer[12927:1633694] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> *** -[NSBundle initWithURL:]: nil URL argument

Any ideas? Thanks in advance

**Comment by ElizaSapir** [comment]
Hey @jonigl,

There are two solutions for this :

Solutions 1: 
1. In Info.plist file add a dictionary with key 'NSAppTransportSecurity'
2. Add another element inside dictionary with key 'Allow Arbitrary Loads'

Plist structure should appear as shown in below image.
![alt tag](http://i.stack.imgur.com/ao49Y.png)

Solution 2 :
1. In Info.plist file add a dictionary with key 'NSAppTransportSecurity'
2. Add another element inside dictionary with key 'NSExceptionDomains'
3. Add element with key 'MyDomainName.com' of type NSDictionary
4. Add element with key 'NSIncludesSubdomains' of type Boolean and value set as YES
5. Add element with key 'NSTemporaryExceptionAllowsInsecureHTTPLoads' of type Boolean and value set as YES

Plist structure should appear as shown in below image.
![alt tag](http://i.stack.imgur.com/Gv9nB.png)

Solution 2 is preferred since it allows only selected domain whereas solution 1 allows all insecure HTTP connections.

**Comment by jonigl** [comment]
Thanks a lot @ElizaSapir for your explanation it is very detailed and solved my problem!!!  :)

**Comment by piterwilson** [comment]
I'm using 2.4 and i still see this, despite having Allo Arbitrary Loads set to TRUE on iOS9 :

`*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull length]: unrecognized selector sent to instance 0x10630fd80`

**Comment by rahul-chowdhary** [comment]
@piterwilson were u able to solve the issue?
