### ISSUE TITLE
Apple TV support

### ISSUE THREAD

**Issue by ProjectDent** [kaltura/player-sdk-native-ios#96]
The player should support Apple TV

**Comment by kaltura-hooks** [comment]
Hi @ProjectDent,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by itaykinnrot** [comment]
Hi @ProjectDent , Thank you for the issue,
We will add support for AppleTV later on, since Apple TV doesnt support webview it will require additional work. If you need something now i suggest you'll download our Client-lib and use the built in player of the Apple-TV in order to show videos. [http://www.kaltura.com/api_v3/testme/client-libs.php]
Thanks,

**Comment by ProjectDent** [comment]
I've spent some time looking at that library. The way it accesses videos is like this:

    NSString *iframeUrl = [[Client instance] getIframeURL:mediaEntry];
    [playerViewController setWebViewURL: iframeUrl];

That `getIframeURL` method defined as:

    - (NSString *)getIframeURL:(KalturaMediaEntry *)mediaEntry{
        return [NSString stringWithFormat:@"http://kgit.html5video.org/tags/v2.0.0.rc12/mwEmbedFrame.php?wid=_%d&uiconf_id=%@&entry_id=%@", partnerId, [self getConfig: @"uiconfID"], mediaEntry.id];
    }

It looks to me like it plays the video from a webview, the url of which that method is generating. Am I correct in thinking that?

And thus, as Apple TV doesn't support webview, this isn't helpful in showing how I'd play a video on Apple TV.

We currently require to display Kaltura video on Apple TV in this next week, and I'd really appreciate any help I could get to make that happen.

**Comment by orenk86** [comment]
Hey guys, any news on this? Will we have tvOS support any time soon?

Thanks!

**Comment by guodongniu** [comment]
Hi, does the player support Apple TV now?

**Comment by ssobhy** [comment]
does the player support TVos now?

**Comment by itaykinnrot** [comment]
Yes:-)

**Comment by amohiy** [comment]
Hi , i am trying to use this player on tvOS and i can not find any default controls(play/pause/..) for the player, is this controls view implemented already or should i implement it from my side ?

**Comment by ejsing** [comment]
What's the difference between playkit-ios and player-sdk-native-ios?
