### ISSUE TITLE
Controls and mid-screen play button remain on screen after full screen button pressed

### ISSUE THREAD

**Issue by ProjectDent** [kaltura/player-sdk-native-ios#97]
1. Initialize `KPViewController`, with `loadPlayerIntoViewController`.
2. Tap full screen.

Play button and controls remain on screen. Tap video, it merely highlights the point of playback you're at. Tap again, it pauses the video. Tap again, it plays the video and dismisses the controls.

**Comment by kaltura-hooks** [comment]
Hi @ProjectDent,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by ElizaSapir** [comment]
Hi @ProjectDent ,

Since it's a view and we can't cover all cases we created a method that overrides our default implementation.

To implement(override) the tap fullscreen button please do the following:
You have to use:
```
@property (nonatomic, copy) void(^fullScreenToggeled)(BOOL isFullScreen);
```
You can find it on `KPViewController`:
 https://github.com/kaltura/player-sdk-native-ios/blob/master/KALTURAPlayerSDK/KPViewController.h#L107

Our [default implementation](https://github.com/kaltura/player-sdk-native-ios/blob/master/KALTURAPlayerSDK/KPViewController.m#L815) is:
```
if (_isFullScreenToggled) {
            self.view.frame = screenBounds();
            [self.topWindow addSubview:self.view];
            [self.topWindow makeKeyAndVisible];
            [self.topWindow.rootViewController.view addSubview:self.view];
        } else {
            self.view.frame = self.superView.bounds;
            [self.superView addSubview:self.view];
        }
```

My advice is to try and use our implementation and REPLACE  `self.topWindow.rootViewController` with `self.topWindow`:

```
if (_isFullScreenToggled) {
            self.view.frame = screenBounds();
            [self.topWindow addSubview:self.view];
            [self.topWindow addSubview:self.view];
        } else {
            self.view.frame = self.superView.bounds;
            [self.superView addSubview:self.view];
        }
```

Let me know if it works for you.

Best,

Eliza
